version: '2.2'
services:
  i2b2-server-srv0:
    extends:
      file: ../docker-compose-common.yml
      service: i2b2-server
    build:
      args:
        - NODE_IDX_ARG=0
        - AXIS2_LOGLEVEL_ARG=DEBUG
        - UNLYNX_DEBUG_LEVEL_ARG=5
    ports:
      - "8082:8080"
      - "9992:9990"
    networks:
      medco-network-srv0:
        aliases:
          - i2b2-server
      cothority-network:
        aliases:
          - i2b2-server-srv0

  i2b2-database-srv0:
    extends:
      file: ../docker-compose-common.yml
      service: i2b2-database
    ports:
      - "5434:5432"
    networks:
      medco-network-srv0:
        aliases:
          - i2b2-database

  i2b2-web-srv0:
    extends:
      file: ../docker-compose-common.yml
      service: i2b2-web
    build:
      args:
        - NODE_IDX_ARG=0
    ports:
      - "82:80"
      - "445:443"
    networks:
      medco-network-srv0:
        aliases:
          - i2b2-web

  unlynx-srv0:
    extends:
      file: ../docker-compose-common.yml
      service: unlynx
    build:
      args:
        - NODE_IDX_ARG=0
        - UNLYNX_DEBUG_LEVEL_ARG=1
    ports:
      - "2002:2002"
      - "2003:2003"
    networks:
      medco-network-srv0:
        aliases:
          - unlynx
      cothority-network:
        aliases:
          - unlynx-srv0
        ipv4_address: 172.16.205.10

  shrine-server-srv0:
    extends:
      file: ../docker-compose-common.yml
      service: shrine-server
    build:
      args:
        - NODE_IDX_ARG=0
        - SHRINE_DEBUG_LEVEL_ARG=FINE
    ports:
      - "6445:6443"
    networks:
      medco-network-srv0:
        aliases:
          - shrine-server
      shrine-network:
        aliases:
          - shrine-server-srv0

  shrine-database-srv0:
    extends:
      file: ../docker-compose-common.yml
      service: shrine-database
    ports:
      - "3308:3306"
    networks:
      medco-network-srv0:
        aliases:
          - shrine-database

networks:
  medco-network-srv0:
    driver: bridge

  medco-network:
    driver: bridge

  cothority-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.205.0/24

  shrine-network:
    driver: bridge
