version: '2.2'
services:
  i2b2-server-srv2:
    extends:
      file: ../docker-compose-common.yml
      service: i2b2-server
    build:
      args:
        - NODE_IDX_ARG=2
        - AXIS2_LOGLEVEL_ARG=DEBUG
        - UNLYNX_DEBUG_LEVEL_ARG=5
    ports:
      - "8086:8080"
      - "9996:9990"
    networks:
      medco-network-srv2:
        aliases:
          - i2b2-server
      cothority-network:
        aliases:
          - i2b2-server-srv2

  i2b2-database-srv2:
    extends:
      file: ../docker-compose-common.yml
      service: i2b2-database
    ports:
      - "5438:5432"
    networks:
      medco-network-srv2:
        aliases:
          - i2b2-database

  i2b2-web-srv2:
    extends:
      file: ../docker-compose-common.yml
      service: i2b2-web
    build:
      args:
        - NODE_IDX_ARG=2
    ports:
      - "86:80"
      - "449:443"
    networks:
      medco-network-srv2:
        aliases:
          - i2b2-web

  unlynx-srv2:
    extends:
      file: ../docker-compose-common.yml
      service: unlynx
    build:
      args:
        - NODE_IDX_ARG=2
        - UNLYNX_DEBUG_LEVEL_ARG=1
    ports:
      - "2006:2006"
      - "2007:2007"
    networks:
      medco-network-srv2:
        aliases:
          - unlynx
      cothority-network:
        aliases:
          - unlynx-srv2
        ipv4_address: 172.16.205.12

  shrine-server-srv2:
    extends:
      file: ../docker-compose-common.yml
      service: shrine-server
    build:
      args:
        - NODE_IDX_ARG=2
        - SHRINE_DEBUG_LEVEL_ARG=DEBUG
    ports:
      - "6449:6443"
    networks:
      medco-network-srv2:
        aliases:
          - shrine-server
      shrine-network:
        aliases:
          - shrine-server-srv2

  shrine-database-srv2:
    extends:
      file: ../docker-compose-common.yml
      service: shrine-database
    ports:
      - "3312:3306"
    networks:
      medco-network-srv2:
        aliases:
          - shrine-database

networks:
  medco-network-srv2:
    driver: bridge

  medco-network:
    external:
      name: dev3nodessamehost_medco-network

  cothority-network:
    external:
      name: dev3nodessamehost_cothority-network

  shrine-network:
    external:
      name: dev3nodessamehost_shrine-network
