Public = ""
Private = ""
Address = ""
Description = ""

[[Secrets]]
  ServerID = "tls://172.31.1.101:2000"
  Secret = "CpCQPCdgvn4oq17fDMdZoMhajfMV2Blz14iU1oCgZQk="

[[Secrets]]
  ServerID = "tls://172.31.1.111:2002"
  Secret = "Rstek34svYAqcCo75aDEC7f8KFSmq34XtQsBgBV0sgE="

[[Secrets]]
  ServerID = "tls://172.31.1.121:2004"
  Secret = "PtooSXjUzZxznTtxLUX0kmjoJOJz0c3j/y2TeLibegw="
