[[servers]]
  Address = "tcp://10.90.38.3:2000"
  Public = "lOEScIjbYAoi0TKn9vgWOPEL8cxAfG1FyIfltFt9bao="
  Description = "Unlynx Server 0 - iccluster027.iccluster"
[[servers]]
  Address = "tcp://10.90.38.4:2000"
  Public = "HC4s0Wzma69jz17cPOY4EtxJOfLJMul6KZH7OmO2Maw="
  Description = "Unlynx Server 1 - iccluster028.iccluster"
[[servers]]
  Address = "tcp://10.90.38.5:2000"
  Public = "RrgkNxmJ0/ButkPdMh2OKyZqu8jak+5pgZH5mmeIrYo="
  Description = "Unlynx Server 2 - iccluster029.iccluster"
[[servers]]
  Address = "tcp://10.90.38.6:2000"
  Public = "NVyd8RO2oma40wYp8vSEb+AtIpgGvzeyh7lbLbA1d+E="
  Description = "Unlynx Server 3 - iccluster030.iccluster"
[[servers]]
  Address = "tcp://10.90.38.7:2000"
  Public = "GU1JgJhl1fuVmAChQTsdfKYQCr1HZ7Za85i8t0l+/hY="
  Description = "Unlynx Server 4 - iccluster031.iccluster"
[[servers]]
  Address = "tcp://10.90.38.8:2000"
  Public = "nTg6h3bLwA6m5lHZGXAProvc/Qf0Mi09W9G3ZjKNwvk="
  Description = "Unlynx Server 5 - iccluster032.iccluster"
[[servers]]
  Address = "tcp://10.90.38.9:2000"
  Public = "ZVdy5FJU+Q83BmOnghRpxSDiiMvzZoJ2XDsq0Bk/5IU="
  Description = "Unlynx Server 6 - iccluster033.iccluster"
[[servers]]
  Address = "tcp://10.90.38.10:2000"
  Public = "higDFuHzvbRox0jNvB+mZhxy3/Ux/tD0dUZ9V/sFJEE="
  Description = "Unlynx Server 7 - iccluster034.iccluster"
[[servers]]
  Address = "tcp://10.90.38.11:2000"
  Public = "KZ9OR3zdmWoMeQx96SWoKY1ls3y3WlEVYQR2om9R26o="
  Description = "Unlynx Server 8 - iccluster035.iccluster"
[[servers]]
  Address = "tcp://10.90.38.13:2000"
  Public = "veTg37pYVSmIbzAtom6fpw3/UU2OtkYD68EeV2j1yDA="
  Description = "Unlynx Server 9 - iccluster037.iccluster"
