Public = ""
Private = ""
Address = ""
Description = ""

[[Secrets]]
  ServerID = "tls://172.31.0.10:2000"
  Secret = "96WM5EtCEbPUyteveLqoPsiLwUZbc1CZrbjDuNX7IAo="

[[Secrets]]
  ServerID = "tls://172.31.0.11:2002"
  Secret = "07zMhs8DmfL9LTHXB0MsglhihtZuDUofN4R++RU7XwU="

[[Secrets]]
  ServerID = "tls://172.31.0.12:2004"
  Secret = "LT7vYTOEViUoIf9PZNuuKHPFntVR9nZJEfagc30ZeA8="
