Public = ""
Private = ""
Address = ""
Description = ""

[[Secrets]]
  ServerID = "tls://172.31.0.10:2000"
  Secret = "zVAb1Ssnbqdu1pGAx9j8lGOepaXCuOzrhaHwohFnOwM="

[[Secrets]]
  ServerID = "tls://172.31.0.11:2002"
  Secret = "bmLfUMBb41qWqYtygxzHBJOtV0rQ7mlzOclj79bABwQ="

[[Secrets]]
  ServerID = "tls://172.31.0.12:2004"
  Secret = "kFlVkaMrO/nUZYslRGio9VBafOqAAeK1sS5mI/ywVQo="
