# This file contains your private key.
# Do not give it away lightly!
Suite = ""
Public = "66dd0ad56eaaa8a1c6b19c62e94cf0743463c5fdd8cf74dc1fac8ed1069d312d"
Private = "2d41ad181fe4f5ddf3c01aeac55538b9b48fec63e98c2de86a531cb66453cd08"
Address = "tls://10.90.39.21:2000"
ListenAddress = ""
Description = "Unlynx Server 1"
WebSocketTLSCertificate = ""
WebSocketTLSCertificateKey = ""
