[[servers]]
  Address = "tcp://10.90.39.12:2000"
  Public = "UE9/SKV6zw3PezdxzDiFXzG776pQRXT2+SyXog7k6Dc="
  Description = "Medco iccluster 1"
[[servers]]
  Address = "tcp://10.90.39.13:2000"
  Public = "LFGVRk/ghvIeGwIFv/ZAFKtM2UWcjSypaVx0YAOdkMU="
  Description = "Medco iccluster 2"
[[servers]]
  Address = "tcp://10.90.39.14:2000"
  Public = "5loqdN2/oXEhkrIEhwc0WCKYm9+c9zs10Y4TZgF6490="
  Description = "Medco iccluster 3"
