version: '2.4'
services:

  prod-i2b2-server-srv2:
    extends:
      file: ../docker-compose-common.yml
      service: i2b2-server
    build:
      args:
        - NODE_IDX_ARG=2
    ports:
      - "8086:8080"
      - "9996:9990"
    volumes:
      - ../../../configuration-profiles/prod/3nodes-samehost:/opt/medco-configuration
    networks:
      medco-network-srv2:
        aliases:
          - i2b2-server
      cothority-network:
        aliases:
          - i2b2-server-srv2
    container_name: prod-i2b2-server-srv2

  prod-i2b2-database-srv2:
    extends:
      file: ../docker-compose-common.yml
      service: i2b2-database
    ports:
      - "5434:5432"
    networks:
      medco-network-srv2:
        aliases:
          - i2b2-database
    container_name: prod-i2b2-database-srv2

  prod-i2b2-web-srv2:
    extends:
      file: ../docker-compose-common.yml
      service: i2b2-web
    build:
      args:
        - NODE_IDX_ARG=2
    ports:
      - "86:80"
      - "449:443"
    volumes:
      - ../../../configuration-profiles/prod/3nodes-samehost:/opt/medco-configuration
    networks:
      medco-network-srv2:
        aliases:
          - i2b2-web
    container_name: prod-i2b2-web-srv2
  
  prod-unlynx-srv2:
    extends:
      file: ../docker-compose-common.yml
      service: unlynx
    build:
      args:
        - NODE_IDX_ARG=2
    ports:
      - "2006:2006"
      - "2007:2007"
    volumes:
      - ../../../configuration-profiles/prod/3nodes-samehost:/opt/medco-configuration
    networks:
      medco-network-srv2:
        aliases:
          - unlynx
      cothority-network:
        aliases:
          - unlynx-srv2
        ipv4_address: 172.16.205.10
    container_name: prod-unlynx-srv2

  prod-shrine-server-srv2:
    extends:
      file: ../docker-compose-common.yml
      service: shrine-server
    build:
      args:
        - NODE_IDX_ARG=2
    ports:
      - "6445:6443"
    networks:
      medco-network-srv2:
        aliases:
          - shrine-server
      shrine-network:
        aliases:
          - shrine-server-srv2
    container_name: prod-shrine-server-srv2

  prod-shrine-database-srv2:
    extends:
      file: ../docker-compose-common.yml
      service: shrine-database
    ports:
      - "3312:3306"
    networks:
      medco-network-srv2:
        aliases:
          - shrine-database
    container_name: prod-shrine-database-srv2

networks:
  medco-network-srv2:
    driver: bridge

  medco-network:
    external:
      name: dev3nodessamehost_medco-network

  cothority-network:
    external:
      name: dev3nodessamehost_cothority-network

  shrine-network:
    external:
      name: dev3nodessamehost_shrine-network