version: '2.4'
services:

  prod-i2b2-server-srv1:
    extends:
      file: ../docker-compose-common.yml
      service: i2b2-server
    build:
      args:
        - NODE_IDX_ARG=1
    ports:
      - "8084:8080"
      - "9994:9990"
    volumes:
      - ../../../configuration-profiles/prod/3nodes-samehost:/opt/medco-configuration
    networks:
      medco-network-srv1:
        aliases:
          - i2b2-server
      cothority-network:
        aliases:
          - i2b2-server-srv1
    container_name: prod-i2b2-server-srv1

  prod-i2b2-database-srv1:
    extends:
      file: ../docker-compose-common.yml
      service: i2b2-database
    ports:
      - "5436:5432"
    networks:
      medco-network-srv1:
        aliases:
          - i2b2-database
    container_name: prod-i2b2-database-srv1

  prod-i2b2-web-srv1:
    extends:
      file: ../docker-compose-common.yml
      service: i2b2-web
    build:
      args:
        - NODE_IDX_ARG=1
    ports:
      - "84:80"
      - "447:443"
    volumes:
      - ../../../configuration-profiles/prod/3nodes-samehost:/opt/medco-configuration
    networks:
      medco-network-srv1:
        aliases:
          - i2b2-web
    container_name: prod-i2b2-web-srv1
  
  prod-unlynx-srv1:
    extends:
      file: ../docker-compose-common.yml
      service: unlynx
    build:
      args:
        - NODE_IDX_ARG=1
    ports:
      - "2004:2004"
      - "2005:2005"
    volumes:
      - ../../../configuration-profiles/prod/3nodes-samehost:/opt/medco-configuration
    networks:
      medco-network-srv1:
        aliases:
          - unlynx
      cothority-network:
        aliases:
          - unlynx-srv1
        ipv4_address: 172.16.205.10
    container_name: prod-unlynx-srv1

  prod-shrine-server-srv1:
    extends:
      file: ../docker-compose-common.yml
      service: shrine-server
    build:
      args:
        - NODE_IDX_ARG=1
    ports:
      - "6447:6443"
    networks:
      medco-network-srv1:
        aliases:
          - shrine-server
      shrine-network:
        aliases:
          - shrine-server-srv1
    container_name: prod-shrine-server-srv1

  prod-shrine-database-srv1:
    extends:
      file: ../docker-compose-common.yml
      service: shrine-database
    ports:
      - "3310:3306"
    networks:
      medco-network-srv1:
        aliases:
          - shrine-database
    container_name: prod-shrine-database-srv1

networks:
  medco-network-srv1:
    driver: bridge

  medco-network:
    external:
      name: dev3nodessamehost_medco-network

  cothority-network:
    external:
      name: dev3nodessamehost_cothority-network

  shrine-network:
    external:
      name: dev3nodessamehost_shrine-network