version: '2.2'
services:
  i2b2-medco:
    extends:
      file: ../docker-compose-common.yml
      service: i2b2-medco
    ports:
    - "8080:8080"
    environment:
      - NODE_IDX=2
    volumes:
      - ../../configuration-profiles/test-3nodes:/medco-configuration

  medco-unlynx:
    extends:
      file: ../docker-compose-common.yml
      service: medco-unlynx
    ports:
      - "2000:2000"
      - "2001:2001"
    environment:
      - NODE_IDX=2
    volumes:
      - ../../configuration-profiles/test-3nodes:/medco-configuration

  web:
    extends:
      file: ../docker-compose-common.yml
      service: web
    environment:
      - CORS_ALLOW_ORIGIN=http://iccluster057.iccluster.epfl.ch:82
    ports:
      - "80:80"
      - "443:443"

  postgresql:
    extends:
      file: ../docker-compose-common.yml
      service: postgresql
    ports:
      - "5432:5432"
