# This file contains your private key.
# Do not give it away lightly!
Suite = ""
Public = "5d55e92ea3fa720f2db8cce9163f34638cd0912cb8542b098047e6e6b05c64b8"
Private = "a451c7b094520802bb93a30309e738a0fe2baa07edb42b2bc0f84fa55f029f0c"
Address = "tls://10.90.39.21:2000"
ListenAddress = ""
Description = "Unlynx Server 1"
WebSocketTLSCertificate = ""
WebSocketTLSCertificateKey = ""
