# This file contains your private key.
# Do not give it away lightly!
Suite = ""
Public = "e8d2112b23d10a2c450ea646a13a6fd12381a8cb22fb05ec4809a3909ac0719c"
Private = "d49fa2a03ae4e1a1f29eeb579009c1211a90d32c995f0bb0d8da25a670e54b0e"
Address = "tls://10.90.40.7:2000"
ListenAddress = ""
Description = "Unlynx Server 3"
WebSocketTLSCertificate = ""
WebSocketTLSCertificateKey = ""
