# This file contains your private key.
# Do not give it away lightly!
Suite = ""
Public = "f3277f602ec60b6d5feec21b22c6f97ac58ff04b3a4131cba86165179c1eed8b"
Private = "f7b015dbde38bca34ed0b03212693614cf1a7abf3542b81dcd49126c4a6dfb01"
Address = "tls://10.90.36.34:2000"
ListenAddress = ""
Description = "Unlynx Server 7"
WebSocketTLSCertificate = ""
WebSocketTLSCertificateKey = ""
