version: '2.4'
services:

  i2b2-server:
    build:
      context: ../../docker-images/prod/i2b2-server
    ports:
      - "8080"
      - "9990"
    networks:
      - medco-network
    volumes:
      - ../../configuration-profiles/dev:/opt/medco-configuration

  unlynx:
    build:
      context: ../../docker-images/prod/unlynx
      args:
        - UNLYNX_DEBUG_LEVEL_ARG=1
    networks:
      - medco-network
    volumes:
      - ../../configuration-profiles/dev:/opt/medco-configuration

