# This file contains your private key.
# Do not give it away lightly!
Suite = ""
Public = "02d0eabbb9eccf09a63f705ec4d4333ff9b492f1fdb72f19c12ec77dcd8bafcf"
Private = "6adf7155710b562fb565e1c09138b42af8951e1966477650413ad1fddb59610c"
Address = "tls://10.90.39.23:2000"
ListenAddress = ""
Description = "Unlynx Server 2"
WebSocketTLSCertificate = ""
WebSocketTLSCertificateKey = ""
