[[servers]]
  Address = "tcp://10.90.38.12:2000"
  Public = "lOEScIjbYAoi0TKn9vgWOPEL8cxAfG1FyIfltFt9bao="
  Description = "MedCo iccluster 1"
[[servers]]
  Address = "tcp://10.90.39.11:2000"
  Public = "HC4s0Wzma69jz17cPOY4EtxJOfLJMul6KZH7OmO2Maw="
  Description = "MedCo iccluster 2"
[[servers]]
  Address = "tcp://10.90.39.12:2000"
  Public = "RrgkNxmJ0/ButkPdMh2OKyZqu8jak+5pgZH5mmeIrYo="
  Description = "MedCo iccluster 3"
[[servers]]
  Address = "tcp://10.90.39.13:2000"
  Public = "NVyd8RO2oma40wYp8vSEb+AtIpgGvzeyh7lbLbA1d+E="
  Description = "MedCo iccluster 4"
[[servers]]
  Address = "tcp://10.90.39.14:2000"
  Public = "GU1JgJhl1fuVmAChQTsdfKYQCr1HZ7Za85i8t0l+/hY="
  Description = "MedCo iccluster 5"
[[servers]]
  Address = "tcp://10.90.39.15:2000"
  Public = "nTg6h3bLwA6m5lHZGXAProvc/Qf0Mi09W9G3ZjKNwvk="
  Description = "MedCo iccluster 6"
[[servers]]
  Address = "tcp://10.90.39.16:2000"
  Public = "ZVdy5FJU+Q83BmOnghRpxSDiiMvzZoJ2XDsq0Bk/5IU="
  Description = "MedCo iccluster 7"
[[servers]]
  Address = "tcp://10.90.39.17:2000"
  Public = "higDFuHzvbRox0jNvB+mZhxy3/Ux/tD0dUZ9V/sFJEE="
  Description = "MedCo iccluster 8"
[[servers]]
  Address = "tcp://10.90.39.18:2000"
  Public = "KZ9OR3zdmWoMeQx96SWoKY1ls3y3WlEVYQR2om9R26o="
  Description = "MedCo iccluster 9"

