version: '2.2'
services:
  i2b2-server:
    extends:
      file: ../docker-compose-common.yml
      service: i2b2-server
    build:
      args:
        - NODE_IDX_ARG=0
        - AXIS2_LOGLEVEL_ARG=INFO
        - UNLYNX_DEBUG_LEVEL_ARG=1
    ports:
      - "8080:8080"
      - "9990:9990"
    volumes:
      - ../configuration-profiles/exp-3nodes-samehost:/opt/medco-configuration

  i2b2-database-datax100:
    extends:
      file: ../docker-compose-common.yml
      service: i2b2-database
    ports:
      - "5432:5432"
    networks:
      medco-network:
        aliases:
          - i2b2-database

  i2b2-web:
    extends:
      file: ../docker-compose-common.yml
      service: i2b2-web
    ports:
      - "80:80"

  unlynx:
    extends:
      file: ../docker-compose-common.yml
      service: unlynx
    build:
      args:
        - NODE_IDX_ARG=0
        - UNLYNX_DEBUG_LEVEL_ARG=1
    ports:
      - "2000:2000"
      - "2001:2001"
    volumes:
      - ../configuration-profiles/exp-3nodes-samehost:/opt/medco-configuration

  shrine-server:
    extends:
      file: ../docker-compose-common.yml
      service: shrine-server
    build:
      args:
        - NODE_IDX_ARG=0
    ports:
      - "6443:6443"
    volumes:
      - ../configuration-profiles/exp-3nodes-samehost:/opt/medco-configuration

  shrine-database:
    extends:
      file: ../docker-compose-common.yml
      service: shrine-database
    ports:
      - "3306:3306"

networks:
  medco-network:
    driver: bridge
