version: '2.4'
services:
  medco-cli-client:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-cli-client
    environment:
      - PICSURE2_API_HOST=${MEDCO_NODE_HOST:?}
      - PICSURE2_API_SCHEME=${MEDCO_NODE_HTTP_SCHEME:?}
      - OIDC_REQ_TOKEN_URL=${MEDCO_NODE_HTTP_SCHEME:?}://${MEDCO_NODE_HOST:?}/auth/realms/master/protocol/openid-connect/token
    volumes:
      - ../../configuration-profiles/test-local-3nodes:/medco-configuration

  medco-loader-srv0:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-loader
    environment:
      - I2B2_DB_NAME=i2b2medcosrv0
      - GA_DB_NAME=gamedcosrv0
      - UNLYNX_GROUP_FILE_IDX=0
      - I2B2_DB_HOST=${MEDCO_NODE_HOST:?}
    volumes:
      - ../../configuration-profiles/test-local-3nodes:/medco-configuration

  medco-loader-srv1:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-loader
    environment:
      - I2B2_DB_NAME=i2b2medcosrv1
      - GA_DB_NAME=gamedcosrv1
      - UNLYNX_GROUP_FILE_IDX=1
      - I2B2_DB_HOST=${MEDCO_NODE_HOST:?}
    volumes:
      - ../../configuration-profiles/test-local-3nodes:/medco-configuration

  medco-loader-srv2:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-loader
    environment:
      - I2B2_DB_NAME=i2b2medcosrv2
      - GA_DB_NAME=gamedcosrv0
      - UNLYNX_GROUP_FILE_IDX=2
      - I2B2_DB_HOST=${MEDCO_NODE_HOST:?}
    volumes:
      - ../../configuration-profiles/test-local-3nodes:/medco-configuration
