version: '2.4'
services:

  prod-i2b2-server:
    extends:
      file: ../docker-compose-common.yml
      service: i2b2-server
    build:
      args:
        - NODE_IDX_ARG=0
    ports:
      - "8080:8080"
      - "9990:9990"
    volumes:
      - ../../../configuration-profiles/3nodes-iccluster:/opt/medco-configuration
    networks:
      - medco-network
    container_name: prod-i2b2-server

  prod-i2b2-database:
    extends:
      file: ../docker-compose-common.yml
      service: i2b2-database
    ports:
      - "5432:5432"
    networks:
      - medco-network
    container_name: prod-i2b2-database

  prod-i2b2-web:
    extends:
      file: ../docker-compose-common.yml
      service: i2b2-web
    build:
      args:
        - NODE_IDX_ARG=0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../../../configuration-profiles/prod/3nodes-samehost:/opt/medco-configuration
    networks:
      - medco-network
    container_name: prod-i2b2-web
  
  prod-unlynx:
    extends:
      file: ../docker-compose-common.yml
      service: unlynx
    build:
      args:
        - NODE_IDX_ARG=0
    ports:
      - "2000:2000"
      - "2001:2001"
    volumes:
      - ../../../configuration-profiles/prod/3nodes-samehost:/opt/medco-configuration
    networks:
      - medco-network
    container_name: prod-unlynx

  prod-shrine-server:
    extends:
      file: ../docker-compose-common.yml
      service: shrine-server
    build:
      args:
        - NODE_IDX_ARG=0
    ports:
      - "6443:6443"
    networks:
      - medco-network
    container_name: prod-shrine-server

  prod-shrine-database:
    extends:
      file: ../docker-compose-common.yml
      service: shrine-database
    ports:
      - "3306:3306"
    networks:
      - medco-network
    container_name: prod-shrine-database

networks:
  medco-network:
    driver: bridge