version: '2.2'
services:
  i2b2-server:
    extends:
      file: ../docker-compose-common.yml
      service: i2b2-server
    build:
      args:
        - UNLYNX_GROUP_KEY_FILE_ARG=exp-10nodes-icclusters/group.toml
        - UNLYNX_ENTRYPOINT_IDX_ARG=5
        - AXIS2_LOGLEVEL_ARG=INFO
        - UNLYNX_DEBUG_LEVEL_ARG=1
    ports:
      - "8080:8080"
      - "9990:9990"

  i2b2-database:
    extends:
      file: ../docker-compose-common.yml
      service: i2b2-database
    ports:
      - "5432:5432"
    networks:
      medco-network:
        aliases:
          - i2b2-database

  i2b2-web:
    extends:
      file: ../docker-compose-common.yml
      service: i2b2-web
    ports:
      - "80:80"

  unlynx:
    extends:
      file: ../docker-compose-common.yml
      service: unlynx
    build:
      args:
        - UNLYNX_KEY_FILE_ARG=exp-10nodes-icclusters/srv5-private.toml
        - UNLYNX_DEBUG_LEVEL_ARG=1
    ports:
      - "2000:2000"
      - "2001:2001"

networks:
  medco-network:
    driver: bridge
