# This file contains your private key.
# Do not give it away lightly!
Suite = ""
Public = "9bde113a1278d5744785151bc763c25da6bc76af5e7c91aa6db829ccdceec4b9"
Private = "6c7cb00df39d02f1071b1c17d3bb6ce350dcb93ce356f14a4ea78b947a461602"
Address = "tls://10.90.39.7:2000"
ListenAddress = ""
Description = "Unlynx Server 0"
WebSocketTLSCertificate = ""
WebSocketTLSCertificateKey = ""
