# This file contains your private key.
# Do not give it away lightly!
Suite = ""
Public = "02b22cd7fe3c50b1a6d028d2f6e6bfc21e2ac4bb2a64d9120bc9f36de6c5b423"
Private = "c24d7e5543810708b0a24199543bd4c7edc9f866bb1fc7209ce28341a1e54b0f"
Address = "tls://10.90.39.21:2000"
ListenAddress = ""
Description = "Unlynx Server 1"
WebSocketTLSCertificate = ""
WebSocketTLSCertificateKey = ""
