# This file contains your private key.
# Do not give it away lightly!
Suite = ""
Public = "7398ff8290fd3088720005824ecfbb6be7cddd524fa52e32ba598caf2417edaa"
Private = "6fedf6f7ffd089fd0553ec1daf54f6dfdf0eda953d1772f7c404d6dbfd84a304"
Address = "tls://10.90.36.32:2000"
ListenAddress = ""
Description = "Unlynx Server 5"
WebSocketTLSCertificate = ""
WebSocketTLSCertificateKey = ""
