# This file contains your private key.
# Do not give it away lightly!
Suite = ""
Public = "e407e2d8846318331d5f75627e2bff5c68f6c5da900ed3c5a434b1f63bf91d2b"
Private = "82ecd2414a0f21766a077affe1c0c69ff1b226c5302190f392b3642ded19db0f"
Address = "tls://10.90.36.34:2000"
ListenAddress = ""
Description = "Unlynx Server 7"
WebSocketTLSCertificate = ""
WebSocketTLSCertificateKey = ""
