# This file contains your private key.
# Do not give it away lightly!
Suite = ""
Public = "36dd0433c4da0a34e0e470482e706a8491d7ebd63b41f2673970b0f7a87f259e"
Private = "a7cfa0ace77d3731ebd8fd7d8c2be50788f8d2ac65f1b539fda3bbe4157a960d"
Address = "tls://10.90.36.35:2000"
ListenAddress = ""
Description = "Unlynx Server 8"
WebSocketTLSCertificate = ""
WebSocketTLSCertificateKey = ""
