[[servers]]
  Address = "tcp://10.90.38.3:2000"
  Public = "lOEScIjbYAoi0TKn9vgWOPEL8cxAfG1FyIfltFt9bao="
  Description = "Unlynx Server 0 - iccluster027.iccluster"
[[servers]]
  Address = "tcp://10.90.38.4:2000"
  Public = "HC4s0Wzma69jz17cPOY4EtxJOfLJMul6KZH7OmO2Maw="
  Description = "Unlynx Server 1 - iccluster028.iccluster"
[[servers]]
  Address = "tcp://10.90.38.5:2000"
  Public = "RrgkNxmJ0/ButkPdMh2OKyZqu8jak+5pgZH5mmeIrYo="
  Description = "Unlynx Server 2 - iccluster029.iccluster"
[[servers]]
  Address = "tcp://10.90.38.6:2000"
  Public = "NVyd8RO2oma40wYp8vSEb+AtIpgGvzeyh7lbLbA1d+E="
  Description = "Unlynx Server 3 - iccluster030.iccluster"
[[servers]]
  Address = "tcp://10.90.38.7:2000"
  Public = "GU1JgJhl1fuVmAChQTsdfKYQCr1HZ7Za85i8t0l+/hY="
  Description = "Unlynx Server 4 - iccluster031.iccluster"
[[servers]]
  Address = "tcp://10.90.38.8:2000"
  Public = "nTg6h3bLwA6m5lHZGXAProvc/Qf0Mi09W9G3ZjKNwvk="
  Description = "Unlynx Server 5 - iccluster032.iccluster"
