[[servers]]
  Address = "tcp://10.90.38.14:2000"
  Public = "5loqdN2/oXEhkrIEhwc0WCKYm9+c9zs10Y4TZgF6490="
  Description = "Unlynx Server 0 - iccluster038.iccluster"
[[servers]]
  Address = "tcp://10.90.38.15:2000"
  Public = "UE9/SKV6zw3PezdxzDiFXzG776pQRXT2+SyXog7k6Dc="
  Description = "Unlynx Server 1 - iccluster039.iccluster"
[[servers]]
  Address = "tcp://10.90.38.16:2000"
  Public = "LFGVRk/ghvIeGwIFv/ZAFKtM2UWcjSypaVx0YAOdkMU="
  Description = "Unlynx Server 2 - iccluster040.iccluster"
