version: '2.2'
services:
  i2b2-medco:
    extends:
      file: ../docker-compose-common.yml
      service: i2b2-medco
    environment:
      - NODE_IDX=${MEDCO_NODE_IDX}
    volumes:
      - ../../configuration-profiles/${MEDCO_PROFILE_NAME}:/medco-configuration

  medco-unlynx:
    extends:
      file: ../docker-compose-common.yml
      service: medco-unlynx
    ports:
      - "2000:2000"
      - "2001:2001"
    environment:
      - NODE_IDX=${MEDCO_NODE_IDX}
    volumes:
      - ../../configuration-profiles/${MEDCO_PROFILE_NAME}:/medco-configuration

  glowing-bear:
    extends:
      file: ../docker-compose-common.yml
      service: glowing-bear
    environment:
      - GB_API_URL=${MEDCO_NODE_URL}/IRCT-CL/rest
      - GB_URL=${MEDCO_NODE_URL}/glowing-bear
      - GB_OIDC_URL=${MEDCO_NODE_URL}/auth/realms/master/protocol/openid-connect
      - GB_OIDC_CLIENT_ID=i2b2-local
      - GB_PICSURE_RES_NAME=i2b2-medco-test-network
      - GB_COTHORITY_KEY_URL=${MEDCO_NODE_URL}/cothority-key.pub.toml
      - GB_GENOMIC_ANNOTATIONS_URL=${MEDCO_NODE_URL}/genomicAnnotations
      - GB_MEDCO_RESULTS_RANDOMIZATION=0

  nginx:
    extends:
      file: ../docker-compose-common.yml
      service: nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - HTTP_SCHEME=https
    volumes:
      - ../../configuration-profiles/${MEDCO_PROFILE_NAME}/group.toml:/medco-configuration/group.toml
      - ../../configuration-profiles/${MEDCO_PROFILE_NAME}/certificate.crt:/medco-configuration/certificate.crt
      - ../../configuration-profiles/${MEDCO_PROFILE_NAME}/certificate.key:/medco-configuration/certificate.key

  php-fpm:
    extends:
      file: ../docker-compose-common.yml
      service: php-fpm
    environment:
      - CORS_ALLOW_ORIGIN=${MEDCO_NODE_URL}

  postgresql:
    extends:
      file: ../docker-compose-common.yml
      service: postgresql
    ports:
      - "5432:5432"

  pg-admin:
    extends:
      file: ../docker-compose-common.yml
      service: pg-admin

  keycloak:
    extends:
      file: ../docker-compose-common.yml
      service: keycloak
    depends_on:
      - postgresql

