version: '2.4'
services:
  medco-cli-client:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-cli-client
    environment:
      - PICSURE2_API_HOST=${MEDCO_CENTRAL_NODE_HOST:?}
      - PICSURE2_API_SCHEME=https
      - PICSURE2_RESOURCES=${PICSURE2_RESOURCES:?}
      - OIDC_REQ_TOKEN_URL=${KEYCLOAK_REALM_URL:?}/protocol/openid-connect/token
      - UNLYNX_GROUP_FILE_IDX=${MEDCO_NODE_IDX:?}
      - OIDC_CLIENT_ID=${KEYCLOAK_CLIENT_ID:?}
    volumes:
      - ../../configuration-profiles/${MEDCO_PROFILE_NAME:?}:/medco-configuration

  medco-loader:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-loader
    environment:
      - UNLYNX_GROUP_FILE_IDX=${MEDCO_NODE_IDX:?}
      - DB_HOST=${MEDCO_NODE_HOST:?}
    volumes:
      - ../../configuration-profiles/${MEDCO_PROFILE_NAME:?}:/medco-configuration