Public = ""
Private = ""
Address = ""
Description = ""

[[Secrets]]
  ServerID = "tls://10.90.40.8:2000"
  Secret = "DENBI9KGtxpLw1paYf7IHyO0MnPWKQlwqbjK4LBn6wc="

[[Secrets]]
  ServerID = "tls://10.90.40.9:2000"
  Secret = "7b09vsWNasJmGp0dtoBJiUj4ntTV+90URCxAsqZdbAk="

[[Secrets]]
  ServerID = "tls://10.90.40.10:2000"
  Secret = "1LAcDGK6SfMzsKd1HfE1SErAjorYm28fnd6yIQo70Ac="
