Public = ""
Private = ""
Address = ""
Description = ""

[[Secrets]]
  ServerID = "tls://10.90.40.8:2000"
  Secret = "M2NB85ANepfdbrau559GLcvB5PoXMWxp98MBozNT5AE="

[[Secrets]]
  ServerID = "tls://10.90.40.9:2000"
  Secret = "wBuAdEVq8xHAkw/X5ricw+wLlRal4ojzlRvfcXEeMw8="

[[Secrets]]
  ServerID = "tls://10.90.40.10:2000"
  Secret = "Js9sXSmrU+dyCpAKFoSMeo/8lt0GTFVL79fOa0DWHQo="
