# This file contains your private key.
# Do not give it away lightly!
Suite = ""
Public = "2d6b30f027b77d7641a422568147e8e8bc582a1e8f0bcff01a6743d6880f5dba"
Private = "0a29e377db6b4a652d816a82b7a6ad4c97cc75e663d284d870cb1b762530c90e"
Address = "tls://10.90.39.7:2000"
ListenAddress = ""
Description = "Unlynx Server 0"
WebSocketTLSCertificate = ""
WebSocketTLSCertificateKey = ""
