# This file contains your private key.
# Do not give it away lightly!
Suite = ""
Public = "8ca22d56c40da2d3778a1d0e2be8625e2fe4765e7ab5f7e66b687c549d9c6bae"
Private = "3d1c60175dde278323d7c1800f6d38561e518c8b33e0ee66dd68411ea60c2702"
Address = "tls://10.90.39.23:2000"
ListenAddress = ""
Description = "Unlynx Server 2"
WebSocketTLSCertificate = ""
WebSocketTLSCertificateKey = ""
