version: '2.2'
services:
  i2b2-server:
    build:
      context: ../i2b2-server
      args:
        - I2B2_DOMAIN_NAME_ARG=medcodeployment
        - UNLYNX_ENTRYPOINT_IDX_ARG=0
        - AXIS2_LOGLEVEL_ARG=INFO
        - UNLYNX_DEBUG_LEVEL_ARG=1
    ports:
      - "8080"
      - "9990"
    networks:
      - medco-network
    volumes:
      - ../configuration-profiles/dev-3nodes-samehost:/opt/medco-configuration

  i2b2-database:
    build:
      context: ../i2b2-database
      args:
        - I2B2_DOMAIN_NAME_ARG=medcodeployment
    ports:
      - "5432"
    networks:
      - medco-network

  i2b2-web:
    build:
      context: ../i2b2-web
      args:
        - I2B2_DOMAIN_NAME_ARG=medcodeployment
    ports:
      - "80"
    networks:
      - medco-network

  unlynx:
    build:
      context: ../unlynx
      args:
        - UNLYNX_ENTRYPOINT_IDX_ARG=0
        - UNLYNX_DEBUG_LEVEL_ARG=1
    ports:
      - "2000"
      - "2001"
    networks:
      - medco-network
    volumes:
      - ../configuration-profiles/dev-3nodes-samehost:/opt/medco-configuration

  shrine-server:
    build:
      context: ../shrine-server
      args:
        - I2B2_DOMAIN_NAME_ARG=medcodeployment
        - SHRINE_NODE_NAME_ARG=172.16.205.10
        - SHRINE_KEYSTORE_PRIVATE_KEY_ALIAS_ARG=172.16.205.10
    ports:
      - "6443"
    networks:
      - medco-network
    volumes:
      - ../configuration-profiles/dev-3nodes-samehost:/opt/medco-configuration

  shrine-database:
    build:
      context: ../shrine-database
      args:
        - I2B2_DOMAIN_NAME_ARG=medcodeployment
    ports:
      - "3306"
    networks:
      - medco-network

networks:
  medco-network:
    driver: bridge
