version: '2.2'
services:
  i2b2-medco:
    image: medco/i2b2-medco:v0.1.1
    environment:
      - I2B2_DB_HOST=postgresql
      - I2B2_DB_PORT=5432
      - I2B2_DB_USER=i2b2
      - I2B2_DB_PW=i2b2
      - I2B2_DB_NAME=i2b2medco
      - WILDFLY_ADMIN_PASSWORD=admin
      - I2B2_DOMAIN_NAME=i2b2medco
      - I2B2_SERVICE_PASSWORD=pFjy3EjDVwLfT2rB9xkK
      - DEFAULT_USER_PASSWORD=demouser
      - NODE_IDX=0
      - UNLYNX_DEBUG_LEVEL=1
      - AXIS2_LOGLEVEL=INFO
    volumes:
      - ../configuration-profiles/dev-3nodes-1host:/medco-configuration

  medco-unlynx:
    image: medco/medco-unlynx:v0.1.1b
    ports:
    - "2000"
    - "2001"
    environment:
    - NODE_IDX=0
    - UNLYNX_DEBUG_LEVEL=1
    volumes:
    - ../configuration-profiles/dev-3nodes-1host:/medco-configuration

  nginx:
    build:
      context: ../docker-images/web
      dockerfile: nginx.Dockerfile
    ports:
      - "80"
      - "443"
    environment:
      - HTTP_SCHEME=http
    volumes:
      - ../docker-images/web/www-data:/www-data
      - ../docker-images/web/nginx-conf.d:/etc/nginx/conf.d
      - ../configuration-profiles/dev-3nodes-1host/group.toml:/medco-configuration/group.toml

  php-fpm:
    build:
      context: ../docker-images/web
      dockerfile: php-fpm.Dockerfile
    environment:
    - I2B2_DB_HOST=postgresql
    - I2B2_DB_PORT=5432
    - I2B2_DB_USER=i2b2
    - I2B2_DB_PW=i2b2
    - I2B2_DB_NAME=i2b2medco
    - I2B2_DOMAIN_NAME=i2b2medco
    - I2B2_URL=http://i2b2-medco:8080/i2b2/services
    - CORS_ALLOW_ORIGIN=http://localhost:4200
    volumes:
    - ../docker-images/web/www-data:/www-data

  postgresql:
    image: postgres:9.6
    environment:
    - POSTGRES_PASSWORD=postgres
    ports:
    - "5432"
    volumes:
    - ../docker-images/postgresql/initdb-data:/docker-entrypoint-initdb.d

  pg-admin:
    build:
      context: ../docker-images/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin
      - PGADMIN_DEFAULT_PASSWORD=admin

  keycloak:
    build:
      context: https://github.com/jboss-dockerfiles/keycloak.git#4.8.2.Final:server
    environment:
      - KEYCLOAK_USER=keycloak
      - KEYCLOAK_PASSWORD=keycloak
      - DB_VENDOR=postgres
      - DB_ADDR=postgresql
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
      - PROXY_ADDRESS_FORWARDING=true

  glowing-bear:
    image: medco/glowing-bear:MedCo-v0.1.1
    ports:
      - "80"
    environment:
      - GB_API_URL=http://localhost/pic-sure/rest
      - GB_URL=http://localhost:82
      - GB_OIDC_URL=http://localhost/auth/realms/master/protocol/openid-connect
      - GB_OIDC_CLIENT_ID=i2b2-local
      - GB_PICSURE_RES_NAME=i2b2-medco-local
      - GB_COTHORITY_KEY_URL=http://localhost/cothority-key.pub.toml
      - GB_GENOMIC_ANNOTATIONS_URL=http://localhost/genomicAnnotations
      - GB_MEDCO_RESULTS_RANDOMIZATION=0
      - GB_FOOTER_TEXT=
