version: '2.4'
services:
  i2b2:
    image: medco/i2b2:${I2B2_VERSION:-v1.0.0-MedCo}
    build:
      context: ../docker-images/i2b2
    environment:
      - I2B2_DB_HOST=postgresql
      - I2B2_DB_PORT=5432
      - I2B2_DB_USER=i2b2
      - I2B2_DB_PW=i2b2
      - I2B2_DB_NAME=i2b2medco
      - WILDFLY_ADMIN_PASSWORD=admin
      - I2B2_DOMAIN_NAME=i2b2medco
      - I2B2_SERVICE_PASSWORD=pFjy3EjDVwLfT2rB9xkK
      - DEFAULT_USER_PASSWORD=demouser
      - AXIS2_LOGLEVEL=INFO
      - MC_DB_HOST=postgresql
      - MC_DB_PORT=5432
      - MC_DB_USER=medcoconnector
      - MC_DB_PW=medcoconnector
      - MC_DB_NAME=medcoconnector

  medco-unlynx:
    image: medco/medco-unlynx:${MEDCO_UNLYNX_VERSION:-v1.0.0}
    environment:
    - NODE_IDX=0
    - UNLYNX_DEBUG_LEVEL=1
    volumes:
    - ../configuration-profiles/dev-local-3nodes:/medco-configuration

  nginx:
    image: medco/nginx:${NGINX_VERSION:-v1.0.0-MedCo}
    build:
      context: ../docker-images/nginx
    environment:
      - HTTP_SCHEME=http
      - ALL_TIMEOUTS_SECONDS=600
      - PROD_CONFIG=false
    volumes:
      - ../docker-images/nginx/www-data:/www-data
      - ../docker-images/nginx/conf.d:/etc/nginx/conf.d

  postgresql:
    image: postgres:9.6
    environment:
    - POSTGRES_PASSWORD=postgres
    volumes:
    - medcodb:/var/lib/postgresql/data
    - ../docker-images/postgresql/initdb-data:/docker-entrypoint-initdb.d

  pg-admin:
    image: medco/pgadmin4:${PGADMIN_VERSION:-v1.0.0-MedCo}
    build:
      context: ../docker-images/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin
      - PGADMIN_DEFAULT_PASSWORD=admin

  keycloak:
    image: medco/keycloak:${KEYCLOAK_VERSION:-v1.0.0-MedCo}
    build:
      context: ../docker-images/keycloak
    environment:
      - KEYCLOAK_USER=keycloak
      - KEYCLOAK_PASSWORD=keycloak
      - DB_VENDOR=postgres
      - DB_ADDR=postgresql
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak

  glowing-bear-medco:
    image: medco/glowing-bear-medco:${GLOWING_BEAR_MEDCO_VERSION:-v1.0.0}
    environment:
      - GB_MEDCO_NODE_URL=http://localhost/local-3nodes/medco-0
      - GB_KEYCLOAK_URL=http://localhost/auth
      - GB_KEYCLOAK_REALM=master
      - GB_KEYCLOAK_CLIENT_ID=medco
      - GB_FOOTER_TEXT=

  medco-connector:
    image: medco/medco-connector:${MEDCO_CONNECTOR_VERSION:-v1.0.0}
    environment:
      - SERVER_HTTP_WRITE_TIMEOUT_SECONDS=600
      - I2B2_HIVE_URL=http://i2b2:8080/i2b2/services
      - I2B2_LOGIN_DOMAIN=i2b2medco
      - I2B2_LOGIN_PROJECT=MedCo
      - I2B2_LOGIN_USER=medcouser
      - I2B2_LOGIN_PASSWORD=demouser
      - I2B2_WAIT_TIME_SECONDS=450
      - LOG_LEVEL=3
      - UNLYNX_GROUP_FILE_PATH=/medco-configuration/group.toml
      - UNLYNX_TIMEOUT_SECONDS=150
      - OIDC_JWKS_URLS=http://keycloak:8080/auth/realms/master/protocol/openid-connect/certs
      - OIDC_JWT_ISSUERS=http://localhost/auth/realms/master
      - OIDC_CLIENT_IDS=medco
      - OIDC_JWT_USER_ID_CLAIMS=preferred_username
      - OIDC_JWKS_TIMEOUT_SECONDS=30
      - MEDCO_OBFUSCATION_MIN=5
      - MEDCO_NODES_URL=http://localhost/local-3nodes/medco-0,http://localhost/local-3nodes/medco-1,http://localhost/local-3nodes/medco-2
      - MEDCO_NODE_IDX=0
      - MC_DB_HOST=postgresql
      - MC_DB_PORT=5432
      - MC_DB_USER=medcoconnector
      - MC_DB_PW=medcoconnector
      - MC_DB_NAME=medcoconnector
      - I2B2_DB_HOST=postgresql
      - I2B2_DB_PORT=5432
      - I2B2_DB_USER=i2b2
      - I2B2_DB_PW=i2b2
      - I2B2_DB_NAME=i2b2medco
    volumes:
      - ../configuration-profiles/dev-local-3nodes:/medco-configuration

  medco-cli-client:
    image: medco/medco-cli-client:${MEDCO_CONNECTOR_VERSION:-v1.0.0}
    environment:
      - LOG_LEVEL=3
      - UNLYNX_GROUP_FILE_PATH=/medco-configuration/group.toml
      - MEDCO_NODE_IDX=0
      - CLIENT_QUERY_TIMEOUT_SECONDS=660
      - CLIENT_GENOMIC_ANNOTATIONS_QUERY_TIMEOUT_SECONDS=10
      - MEDCO_CONNECTOR_URL=http://localhost/local-3nodes/medco-0
      - OIDC_REQ_TOKEN_URL=http://localhost/auth/realms/master/protocol/openid-connect/token
      - OIDC_REQ_TOKEN_CLIENT_ID=medco
    volumes:
      - ../configuration-profiles/dev-local-3nodes:/medco-configuration
      - ./:/results
    network_mode: host

  medco-loader:
    image: medco/medco-loader:${MEDCO_LOADER_VERSION:-v1.0.0}
    environment:
      - LOG_LEVEL=3
      - UNLYNX_GROUP_FILE_PATH=/medco-configuration/group.toml
      - UNLYNX_GROUP_FILE_IDX=0
      - I2B2_DB_HOST=localhost
      - I2B2_DB_PORT=5432
      - I2B2_DB_NAME=i2b2medco
      - I2B2_DB_USER=i2b2
      - I2B2_DB_PASSWORD=i2b2
      - MC_DB_HOST=localhost
      - MC_DB_PORT=5432
      - MC_DB_NAME=medcoconnector
      - MC_DB_USER=medcoconnector
      - MC_DB_PASSWORD=medcoconnector
    volumes:
      - ../resources/data:/data
      - ../configuration-profiles/dev-local-3nodes:/medco-configuration
    network_mode: host
