version: '2.4'
services:
  i2b2:
    image: medco/i2b2:${I2B2_VERSION:-MedCo-v0.2.1}
    build:
      context: ../docker-images/i2b2
    environment:
      - I2B2_DB_HOST=postgresql
      - I2B2_DB_PORT=5432
      - I2B2_DB_USER=i2b2
      - I2B2_DB_PW=i2b2
      - I2B2_DB_NAME=i2b2medcosrv
      - WILDFLY_ADMIN_PASSWORD=admin
      - I2B2_DOMAIN_NAME=i2b2medco
      - I2B2_SERVICE_PASSWORD=pFjy3EjDVwLfT2rB9xkK
      - DEFAULT_USER_PASSWORD=demouser
      - AXIS2_LOGLEVEL=INFO

  medco-unlynx:
    image: medco/medco-unlynx:${MEDCO_UNLYNX_VERSION:-v0.2.1}
    ports:
    - "2000"
    - "2001"
    environment:
    - NODE_IDX=0
    - UNLYNX_DEBUG_LEVEL=1
    volumes:
    - ../configuration-profiles/dev-local-3nodes:/medco-configuration

  nginx:
    image: medco/nginx:${NGINX_VERSION:-MedCo-v0.2.1}
    build:
      context: ../docker-images/nginx
    ports:
      - "80"
      - "443"
    environment:
      - HTTP_SCHEME=http
      - ALL_TIMEOUTS_SECONDS=600
    volumes:
      - ../docker-images/nginx/www-data:/www-data
      - ../docker-images/nginx/conf.d:/etc/nginx/conf.d
      - ../configuration-profiles/dev-local-3nodes/group.toml:/medco-configuration/group.toml

  postgresql:
    image: postgres:9.6
    environment:
    - POSTGRES_PASSWORD=postgres
    ports:
    - "5432"
    volumes:
    - ../docker-images/postgresql/initdb-data:/docker-entrypoint-initdb.d

  pg-admin:
    image: medco/pgadmin4:${PGADMIN_VERSION:-MedCo-v0.2.1}
    build:
      context: ../docker-images/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin
      - PGADMIN_DEFAULT_PASSWORD=admin

  keycloak:
    image: medco/keycloak:${KEYCLOAK_VERSION:-MedCo-v0.2.1}
    build:
      context: ../docker-images/keycloak
    environment:
      - KEYCLOAK_USER=keycloak
      - KEYCLOAK_PASSWORD=keycloak
      - DB_VENDOR=postgres
      - DB_ADDR=postgresql
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak

  glowing-bear-medco:
    image: medco/glowing-bear-medco:${GLOWING_BEAR_MEDCO_VERSION:-v0.2.1}
    ports:
      - "80"
    environment:
      - GB_API_URL=http://localhost/pic-sure-api-2/PICSURE
      - GB_URL=http://localhost:82
      - GB_OIDC_URL=http://localhost/auth/realms/master/protocol/openid-connect
      - GB_OIDC_CLIENT_ID=medco
      - GB_COTHORITY_KEY_URL=http://localhost/cothority-key.pub.toml
      - GB_GENOMIC_ANNOTATIONS_URL=http://localhost/genomicAnnotations
      - GB_MEDCO_RESULTS_RANDOMIZATION=0
      - GB_FOOTER_TEXT=
      - MEDCO_NETWORK_NAME=testnetwork
      - MEDCO_NODES_NAME=a,b,c

  medco-connector:
    image: medco/medco-connector:${MEDCO_CONNECTOR_VERSION:-v0.2.1}
    ports:
      - "1999"
    environment:
      - SERVER_HTTP_WRITE_TIMEOUT_SECONDS=600
      - I2B2_HIVE_URL=http://i2b2:8080/i2b2/services
      - I2B2_LOGIN_DOMAIN=i2b2medco
      - I2B2_LOGIN_PROJECT=MedCo
      - I2B2_LOGIN_USER=medcouser
      - I2B2_LOGIN_PASSWORD=demouser
      - I2B2_WAIT_TIME_SECONDS=450
      - LOG_LEVEL=3
      - UNLYNX_GROUP_FILE_PATH=/medco-configuration/group.toml
      - UNLYNX_TIMEOUT_SECONDS=150
      - JWKS_URL=http://keycloak:8080/auth/realms/master/protocol/openid-connect/certs
      - OIDC_JWT_ISSUER=http://localhost/auth/realms/master
      - OIDC_CLIENT_ID=medco
      - OIDC_JWT_USER_ID_CLAIM=preferred_username
      - MEDCO_OBFUSCATION_MIN=5
      - MEDCO_NODES_URL=http://localhost/local-3nodes/medco-0,http://localhost/local-3nodes/medco-1,http://localhost/local-3nodes/medco-2
      - MEDCO_NODE_IDX=0
      - GA_DB_HOST=postgresql
      - GA_DB_PORT=5432
      - GA_DB_USER=genomicannotations
      - GA_DB_PW=genomicannotations
      - GA_DB_NAME=gamedcosrv
    volumes:
      - ../configuration-profiles/dev-local-3nodes:/medco-configuration

  medco-cli-client:
    image: medco/medco-cli-client:${MEDCO_CONNECTOR_VERSION:-v0.2.1}
    environment:
      - LOG_LEVEL=3
      - UNLYNX_GROUP_FILE_PATH=/medco-configuration/group.toml
      - MEDCO_NODE_IDX=0
      - OIDC_CLIENT_ID=medco
      - CLIENT_QUERY_TIMEOUT_SECONDS=660
      - CLIENT_GENOMIC_ANNOTATIONS_QUERY_TIMEOUT_SECONDS=10
      - MEDCO_CONNECTOR_URL=http://localhost:1990/medco
      - OIDC_REQ_TOKEN_URL=http://localhost/auth/realms/master/protocol/openid-connect/token
    volumes:
      - ../configuration-profiles/dev-local-3nodes:/medco-configuration
    network_mode: host

  medco-loader:
    image: medco/medco-loader:${MEDCO_LOADER_VERSION:-v0.2.1}
    environment:
      - LOG_LEVEL=3
      - UNLYNX_GROUP_FILE_PATH=/medco-configuration/group.toml
      - UNLYNX_GROUP_FILE_IDX=0
      - I2B2_DB_HOST=localhost
      - I2B2_DB_PORT=5432
      - I2B2_DB_NAME=i2b2medcosrv
      - I2B2_DB_USER=i2b2
      - I2B2_DB_PASSWORD=i2b2
    volumes:
      - ../resources/data:/data
      - ../configuration-profiles/dev-local-3nodes:/medco-configuration
    network_mode: host
