version: '2.2'
services:
  i2b2-server:
    build:
      context: ../docker-images/i2b2-server
      args:
        - I2B2_DOMAIN_NAME_ARG=medcodeployment
        - NODE_IDX_ARG=0
        - AXIS2_LOGLEVEL_ARG=INFO
        - UNLYNX_DEBUG_LEVEL_ARG=1
    ports:
      - "8080"
      - "9990"
    networks:
      - medco-network
    volumes:
      - ../configuration-profiles/dev-3nodes-samehost:/opt/medco-configuration

  i2b2-database:
    build:
      context: ../docker-images/i2b2-database
      args:
        - I2B2_DOMAIN_NAME_ARG=medcodeployment
    ports:
      - "5432"
    networks:
      - medco-network

  i2b2-web:
    build:
      context: ../docker-images/i2b2-web
      args:
        - NODE_IDX_ARG=0
        - I2B2_DOMAIN_NAME_ARG=medcodeployment
    ports:
      - "80"
      - "443"
    networks:
      - medco-network
    volumes:
      - ../configuration-profiles/dev-3nodes-samehost:/opt/medco-configuration

  unlynx:
    build:
      context: ../docker-images/unlynx
      args:
        - NODE_IDX_ARG=0
        - UNLYNX_DEBUG_LEVEL_ARG=1
    ports:
      - "2000"
      - "2001"
    networks:
      - medco-network
    volumes:
      - ../configuration-profiles/dev-3nodes-samehost:/opt/medco-configuration

  shrine-server:
    build:
      context: ../docker-images/shrine-server
      args:
        - I2B2_DOMAIN_NAME_ARG=medcodeployment
        - NODE_IDX_ARG=0
        - SHRINE_DEBUG_LEVEL_ARG=INFO
    ports:
      - "6443"
    networks:
      - medco-network
    volumes:
      - ../configuration-profiles/dev-3nodes-samehost:/opt/medco-configuration

  shrine-database:
    build:
      context: ../docker-images/shrine-database
      args:
        - I2B2_DOMAIN_NAME_ARG=medcodeployment
    ports:
      - "3306"
    networks:
      - medco-network

networks:
  medco-network:
    driver: bridge
