version: '2.4'
services:
  i2b2-srv0:
    extends:
      file: ../docker-compose-common.yml
      service: i2b2
    image: medco/i2b2:v1.7.10.0001-MedCo-dev
    environment:
      - I2B2_DB_NAME=i2b2medcosrv0
      - I2B2_DOMAIN_NAME=i2b2medcosrv0
      - AXIS2_LOGLEVEL=DEBUG
    ports:
      - "8090:8080"
    networks:
      medco-srv0:
        aliases:
          - i2b2
      medco-network:
      keycloak-network:

  medco-unlynx-srv0:
    extends:
      file: ../docker-compose-common.yml
      service: medco-unlynx
    image: medco/medco-unlynx:dev
    ports:
      - "2000:2000"
      - "2001:2001"
    environment:
      - NODE_IDX=0
      - UNLYNX_DEBUG_LEVEL=3
    networks:
      medco-srv0:
      medco-network:
        ipv4_address: 172.31.0.10

  medco-connector-srv0:
    extends:
      file: ../docker-compose-common.yml
      service: medco-connector
    image: medco/medco-connector:dev
    ports:
      - "1990:1999"
    environment:
      - I2B2_HIVE_URL=http://i2b2-srv0:8080/i2b2/services
      - I2B2_LOGIN_DOMAIN=i2b2medcosrv0
      - LOG_LEVEL=5
      - UNLYNX_GROUP_FILE_IDX=0
    networks:
      - medco-srv0
      - medco-network
      - keycloak-network

  i2b2-srv1:
    extends:
      file: ../docker-compose-common.yml
      service: i2b2
    image: medco/i2b2:v1.7.10.0001-MedCo-dev
    environment:
      - I2B2_DB_NAME=i2b2medcosrv1
      - I2B2_DOMAIN_NAME=i2b2medcosrv1
      - AXIS2_LOGLEVEL=DEBUG
    ports:
      - "8091:8080"
    networks:
      medco-srv1:
        aliases:
          - i2b2
      medco-network:
      keycloak-network:

  medco-unlynx-srv1:
    extends:
      file: ../docker-compose-common.yml
      service: medco-unlynx
    image: medco/medco-unlynx:dev
    ports:
      - "2002:2002"
      - "2003:2003"
    environment:
      - NODE_IDX=1
      - UNLYNX_DEBUG_LEVEL=3
    networks:
      medco-srv1:
      medco-network:
        ipv4_address: 172.31.0.11

  medco-connector-srv1:
    extends:
      file: ../docker-compose-common.yml
      service: medco-connector
    image: medco/medco-connector:dev
    ports:
      - "1991:1999"
    environment:
      - I2B2_HIVE_URL=http://i2b2-srv1:8080/i2b2/services
      - I2B2_LOGIN_DOMAIN=i2b2medcosrv1
      - LOG_LEVEL=5
      - UNLYNX_GROUP_FILE_IDX=1
    networks:
      - medco-srv1
      - medco-network
      - keycloak-network

  i2b2-srv2:
    extends:
      file: ../docker-compose-common.yml
      service: i2b2
    image: medco/i2b2:v1.7.10.0001-MedCo-dev
    environment:
      - I2B2_DB_NAME=i2b2medcosrv2
      - I2B2_DOMAIN_NAME=i2b2medcosrv2
      - AXIS2_LOGLEVEL=DEBUG
    ports:
      - "8092:8080"
    networks:
      medco-srv2:
        aliases:
          - i2b2
      medco-network:
      keycloak-network:

  medco-unlynx-srv2:
    extends:
      file: ../docker-compose-common.yml
      service: medco-unlynx
    image: medco/medco-unlynx:dev
    ports:
      - "2004:2004"
      - "2005:2005"
    environment:
      - NODE_IDX=2
      - UNLYNX_DEBUG_LEVEL=3
    networks:
      medco-srv2:
      medco-network:
        ipv4_address: 172.31.0.12

  medco-connector-srv2:
    extends:
      file: ../docker-compose-common.yml
      service: medco-connector
    image: medco/medco-connector:dev
    ports:
      - "1992:1999"
    environment:
      - I2B2_HIVE_URL=http://i2b2-srv2:8080/i2b2/services
      - I2B2_LOGIN_DOMAIN=i2b2medcosrv2
      - LOG_LEVEL=5
      - UNLYNX_GROUP_FILE_IDX=2
    networks:
      - medco-srv2
      - medco-network
      - keycloak-network

  nginx:
    extends:
      file: ../docker-compose-common.yml
      service: nginx
    ports:
    - "80:80"
    environment:
    - HTTP_SCHEME=http
    networks:
    - medco-srv0
    - keycloak-network

  php-fpm:
    extends:
      file: ../docker-compose-common.yml
      service: php-fpm
    environment:
    - I2B2_DB_NAME=i2b2medcosrv0
    - I2B2_DOMAIN_NAME=i2b2medcosrv0
    - I2B2_URL=http://i2b2-medco-srv0:8080/i2b2/services
    networks:
    - medco-srv0

  postgresql:
    extends:
      file: ../docker-compose-common.yml
      service: postgresql
    ports:
      - "5432:5432"
    networks:
      - medco-srv0
      - medco-srv1
      - medco-srv2
      - keycloak-network

  pg-admin:
    extends:
      file: ../docker-compose-common.yml
      service: pg-admin
    ports:
      - "81:80"
    networks:
      - medco-srv0
      - medco-srv1
      - medco-srv2

  keycloak:
    extends:
      file: ../docker-compose-common.yml
      service: keycloak
    ports:
      - "8081:8080"
    depends_on:
      - postgresql
    networks:
      - keycloak-network

  picsure:
    extends:
      file: ../docker-compose-common.yml
      service: picsure
    ports:
      - "8082:8080"
      - "9992:9990"
    depends_on:
      - postgresql
    networks:
      - medco-srv0
      - medco-srv1
      - medco-srv2
      - keycloak-network

networks:
  medco-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/24

  keycloak-network:
    driver: bridge

  medco-srv0:
    driver: bridge
  medco-srv1:
    driver: bridge
  medco-srv2:
    driver: bridge
