version: '2.4'
services:
  medco-cli-client:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-cli-client
    environment:
      - LOG_LEVEL=5

  medco-loader-srv0:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-loader
    environment:
      - LOG_LEVEL=5
      - I2B2_DB_NAME=i2b2medcosrv0
      - GA_DB_NAME=gamedcosrv0
      - UNLYNX_GROUP_FILE_IDX=0

  medco-loader-srv1:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-loader
    environment:
      - LOG_LEVEL=5
      - I2B2_DB_NAME=i2b2medcosrv1
      - GA_DB_NAME=gamedcosrv1
      - UNLYNX_GROUP_FILE_IDX=1

  medco-loader-srv2:
    extends:
      file: ../docker-compose-definitions.yml
      service: medco-loader
    environment:
      - LOG_LEVEL=5
      - I2B2_DB_NAME=i2b2medcosrv2
      - GA_DB_NAME=gamedcosrv2
      - UNLYNX_GROUP_FILE_IDX=2
