version: '2.2'
services:
  i2b2-medco-srv0:
    extends:
      file: ../docker-compose-common.yml
      service: i2b2-medco
    image: medco/i2b2-medco:dev
    environment:
      - I2B2_DB_NAME=i2b2medcosrv0
      - I2B2_DOMAIN_NAME=i2b2medcosrv0
      - NODE_IDX=0
      - UNLYNX_DEBUG_LEVEL=2
      - AXIS2_LOGLEVEL=DEBUG
    ports:
      - "8090:8080"
    networks:
      medco-srv0:
        aliases:
        - i2b2
      medco-network:
      keycloak-network:
    volumes:
      - ../../configuration-profiles/dev-3nodes-1host:/medco-configuration

  medco-unlynx-srv0:
    extends:
      file: ../docker-compose-common.yml
      service: medco-unlynx
    image: medco/medco-unlynx:dev
    ports:
      - "2000:2000"
      - "2001:2001"
    environment:
      - NODE_IDX=0
      - UNLYNX_DEBUG_LEVEL=2
    networks:
      - medco-srv0
      - medco-network
    volumes:
      - ../../configuration-profiles/dev-3nodes-1host:/medco-configuration

  i2b2-medco-srv1:
    extends:
      file: ../docker-compose-common.yml
      service: i2b2-medco
    image: medco/i2b2-medco:dev
    environment:
      - I2B2_DB_NAME=i2b2medcosrv1
      - I2B2_DOMAIN_NAME=i2b2medcosrv1
      - NODE_IDX=1
      - UNLYNX_DEBUG_LEVEL=2
      - AXIS2_LOGLEVEL=DEBUG
    ports:
      - "8091:8080"
    networks:
      medco-srv1:
        aliases:
          - i2b2
      medco-network:
      keycloak-network:
    volumes:
      - ../../configuration-profiles/dev-3nodes-1host:/medco-configuration

  medco-unlynx-srv1:
    extends:
      file: ../docker-compose-common.yml
      service: medco-unlynx
    image: medco/medco-unlynx:dev
    ports:
      - "2002:2002"
      - "2003:2003"
    environment:
      - NODE_IDX=1
      - UNLYNX_DEBUG_LEVEL=2
    networks:
      - medco-srv1
      - medco-network
    volumes:
      - ../../configuration-profiles/dev-3nodes-1host:/medco-configuration

  i2b2-medco-srv2:
    extends:
      file: ../docker-compose-common.yml
      service: i2b2-medco
    image: medco/i2b2-medco:dev
    environment:
      - I2B2_DB_NAME=i2b2medcosrv2
      - I2B2_DOMAIN_NAME=i2b2medcosrv2
      - NODE_IDX=2
      - UNLYNX_DEBUG_LEVEL=2
      - AXIS2_LOGLEVEL=DEBUG
    ports:
      - "8092:8080"
    networks:
      medco-srv2:
        aliases:
          - i2b2
      medco-network:
      keycloak-network:
    volumes:
      - ../../configuration-profiles/dev-3nodes-1host:/medco-configuration

  medco-unlynx-srv2:
    extends:
      file: ../docker-compose-common.yml
      service: medco-unlynx
    image: medco/medco-unlynx:dev
    ports:
      - "2004:2004"
      - "2005:2005"
    environment:
      - NODE_IDX=2
      - UNLYNX_DEBUG_LEVEL=2
    networks:
      - medco-srv2
      - medco-network
    volumes:
      - ../../configuration-profiles/dev-3nodes-1host:/medco-configuration

  nginx:
    extends:
      file: ../docker-compose-common.yml
      service: nginx
    ports:
    - "80:80"
    environment:
    - HTTP_SCHEME=http
    networks:
    - medco-srv0
    - keycloak-network
    volumes:
    - ../../configuration-profiles/dev-3nodes-1host/group.toml:/medco-configuration/group.toml
    - ../../configuration-profiles/dev-3nodes-1host/certificate.crt:/medco-configuration/certificate.crt
    - ../../configuration-profiles/dev-3nodes-1host/certificate.key:/medco-configuration/certificate.key

  php-fpm:
    extends:
      file: ../docker-compose-common.yml
      service: php-fpm
    environment:
    - I2B2_DB_NAME=i2b2medcosrv0
    - I2B2_DOMAIN_NAME=i2b2medcosrv0
    - I2B2_URL=http://i2b2-medco-srv0:8080/i2b2/services
    networks:
    - medco-srv0

  postgresql:
    extends:
      file: ../docker-compose-common.yml
      service: postgresql
    ports:
      - "5432:5432"
    networks:
      - medco-srv0
      - medco-srv1
      - medco-srv2
      - keycloak-network

  pg-admin:
    extends:
      file: ../docker-compose-common.yml
      service: pg-admin
    ports:
      - "81:80"
    networks:
      - medco-srv0
      - medco-srv1
      - medco-srv2

  keycloak:
    extends:
      file: ../docker-compose-common.yml
      service: keycloak
    ports:
      - "8081:8080"
    depends_on:
      - postgresql
    networks:
      - keycloak-network

networks:
  medco-network:
    driver: bridge

  keycloak-network:
    driver: bridge

  medco-srv0:
    driver: bridge
  medco-srv1:
    driver: bridge
  medco-srv2:
    driver: bridge
