Public = ""
Private = ""
Address = ""
Description = ""

[[Secrets]]
  ServerID = "tcp://172.16.205.10:2002"
  Secret = "iKLji6KBqr25fQcaOhSEzJ8+fNgFp3Jg3rMQnLdwOQ4="

[[Secrets]]
  ServerID = "tcp://172.16.205.11:2004"
  Secret = "aDLLpnq6VMzKD5MG1GuqCBnD4HLlJi0c3/PBqqqcegw="

[[Secrets]]
  ServerID = "tcp://172.16.205.12:2006"
  Secret = "pvy+eXRtna8TxdPV4dC+NNosaZ01V2T6ALh2QnEcBw8="
