Public = ""
Private = ""
Address = ""
Description = ""

[[Secrets]]
  ServerID = "tcp://172.16.205.10:2002"
  Secret = "beycqQF6pHTYm5af12ciKJN142iqhvL5JvnpWpC6Fg8="

[[Secrets]]
  ServerID = "tcp://172.16.205.11:2004"
  Secret = "1JInL8jvPntV6/uhn6aD3iaQuTTjzbwlVSHaWSWWkQE="

[[Secrets]]
  ServerID = "tcp://172.16.205.12:2006"
  Secret = "JXLuaQB11/BwNWUrdVzksPQyNMGC7bwVHpJl+xM6nQI="
