Public = ""
Private = ""
Address = ""
Description = ""

[[Secrets]]
  ServerID = "tcp://172.16.205.10:2002"
  Secret = "Hy/CwGM4jNg6s0szZlHFl8Sht0v+W0oRfC0vFM+GJQs="

[[Secrets]]
  ServerID = "tcp://172.16.205.11:2004"
  Secret = "kxzSL486Gwe0tV/aTht7Gd/XeiAH9YGi5waQOMPvWwA="

[[Secrets]]
  ServerID = "tcp://172.16.205.12:2006"
  Secret = "tSuoL1gPSQOhnBQ/twWwvWNWdhiRIrQx63k+jbPxRQk="
