version: '2.2'
services:
  i2b2-server:
    extends:
      file: ../docker-compose-common.yml
      service: i2b2-server
    build:
      args:
        - NODE_IDX_ARG=2
    ports:
      - "8082:8080"
      - "9992:9990"
    volumes:
      - ../../configuration-profiles/exp-6nodes-icclusters-1CA:/opt/medco-configuration
    networks:
      - medco-network-srv2

  i2b2-database:
    extends:
      file: ../docker-compose-common.yml
      service: i2b2-database
    ports:
      - "5434:5432"
    networks:
      - medco-network-srv2

  i2b2-web:
    extends:
      file: ../docker-compose-common.yml
      service: i2b2-web
    build:
      args:
        - NODE_IDX_ARG=2
    ports:
      - "82:80"
      - "445:443"
    volumes:
      - ../../configuration-profiles/exp-6nodes-icclusters-1CA:/opt/medco-configuration
    networks:
      - medco-network-srv2

  unlynx:
    extends:
      file: ../docker-compose-common.yml
      service: unlynx
    build:
      args:
        - NODE_IDX_ARG=2
    ports:
      - "2002:2000"
      - "2003:2001"
    volumes:
      - ../../configuration-profiles/exp-6nodes-icclusters-1CA:/opt/medco-configuration
    networks:
      - medco-network-srv2

  shrine-server:
    extends:
      file: ../docker-compose-common.yml
      service: shrine-server
    build:
      args:
        - NODE_IDX_ARG=2
    ports:
      - "6445:6443"
    volumes:
      - ../../configuration-profiles/exp-6nodes-icclusters-1CA:/opt/medco-configuration
    networks:
      - medco-network-srv2

  shrine-database:
    extends:
      file: ../docker-compose-common.yml
      service: shrine-database
    ports:
      - "3308:3306"
    networks:
      - medco-network-srv2

networks:
  medco-network-srv2:
    driver: bridge
