version: '2.2'
services:
  i2b2-server-srv0:
    extends:
      file: ../docker-compose-common.yml
      service: i2b2-server
    build:
      args:
        - NODE_IDX_ARG=0
    ports:
      - "8082:8080"
      - "9992:9990"
    volumes:
      - ../../configuration-profiles/exp-6nodes-icclusters-1CA:/opt/medco-configuration
    networks:
      medco-network-srv0:
        aliases:
          - i2b2-server

  i2b2-database-srv0:
    extends:
      file: ../docker-compose-common.yml
      service: i2b2-database
    ports:
      - "5434:5432"
    networks:
      medco-network-srv0:
        aliases:
          - i2b2-database

  i2b2-web-srv0:
    extends:
      file: ../docker-compose-common.yml
      service: i2b2-web
    build:
      args:
        - NODE_IDX_ARG=0
    ports:
      - "82:80"
      - "445:443"
    volumes:
      - ../../configuration-profiles/exp-6nodes-icclusters-1CA:/opt/medco-configuration
    networks:
      medco-network-srv0:
        aliases:
          - i2b2-web

  unlynx-srv0:
    extends:
      file: ../docker-compose-common.yml
      service: unlynx
    build:
      args:
        - NODE_IDX_ARG=0
    ports:
      - "2002:2002"
      - "2003:2003"
    volumes:
      - ../../configuration-profiles/exp-6nodes-icclusters-1CA:/opt/medco-configuration
    networks:
      medco-network-srv0:
        aliases:
          - unlynx

  shrine-server-srv0:
    extends:
      file: ../docker-compose-common.yml
      service: shrine-server
    build:
      args:
        - NODE_IDX_ARG=0
    ports:
      - "6445:6443"
    volumes:
      - ../../configuration-profiles/exp-6nodes-icclusters-1CA:/opt/medco-configuration
    networks:
      medco-network-srv0:
        aliases:
          - shrine-server

  shrine-database-srv0:
    extends:
      file: ../docker-compose-common.yml
      service: shrine-database
    ports:
      - "3308:3306"
    networks:
      medco-network-srv0:
        aliases:
          - shrine-database

networks:
  medco-network-srv0:
    driver: bridge
